name: ems_effect
channels:
  - bioconda
  - r
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.13=hb9d3cd8_0
  - bcbio-gff=0.7.1=pyh7e72e81_2
  - binutils_impl_linux-64=2.43=h4bf12b8_2
  - biopython=1.85=py312h66e93f0_1
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bwidget=1.10.1=ha770c72_0
  - bx-python=0.13.0=py312h5e9d817_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cairo=1.18.2=h3394656_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.1=py312h68727a3_0
  - curl=8.11.1=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.0=h59595ed_0
  - expat=2.6.4=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.8=py312h178313f_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=14.2.0=h6b349bd_1
  - gfortran_impl_linux-64=14.2.0=hc73f493_1
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=14.2.0=h2c03514_1
  - harfbuzz=10.2.0=h4bba637_0
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=28_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=28_he106b2a_openblas
  - libclang-cpp19.1=19.1.7=default_hb5137d0_1
  - libclang13=19.1.7=default_h9c6a7e4_1
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.11.1=h332b0f4_0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=14.2.0=h41c2201_101
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=28_h7ac8fdf_openblas
  - libllvm19=19.1.7=ha7bfdaf_1
  - liblzma=5.6.4=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.46=h943b412_0
  - libpq=17.2=h3b95a9b_1
  - libsanitizer=14.2.0=h2a3dede_1
  - libsqlite=3.48.0=hee588c1_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=14.2.0=h41c2201_101
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=hc4654cb_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.13.5=h8d12d68_1
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - matplotlib=3.10.0=py312h7900ff3_0
  - matplotlib-base=3.10.0=py312hd3ec401_0
  - munkres=1.0.7=py_1
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - ncurses=6.5=h2d0b736_3
  - numpy=2.2.2=py312h72c5963_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.4.0=h7b32b05_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312hf9745cd_1
  - pandoc=3.6.3=ha770c72_0
  - pango=1.56.1=h861ebed_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=hba22ea6_2
  - pillow=11.1.0=py312h80c1187_0
  - pip=25.0=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pysam=0.23.0=py312h47d5410_0
  - pyside6=6.8.1=py312h91f0f75_0
  - python=3.12.8=h9e4cc4f_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.8.1=h588cce1_2
  - r-argparse=2.2.5=r43hc72bb7e_0
  - r-askpass=1.2.1=r43h2b5f3a1_0
  - r-assertthat=0.2.1=r43hc72bb7e_5
  - r-backports=1.5.0=r43hb1dbf0f_1
  - r-base=4.3.3=h5074ccb_16
  - r-base64enc=0.1_3=r43hb1dbf0f_1007
  - r-bit=4.5.0.1=r43h2b5f3a1_0
  - r-bit64=4.5.2=r43h2b5f3a1_0
  - r-blob=1.2.4=r43hc72bb7e_2
  - r-broom=1.0.7=r43hc72bb7e_0
  - r-bslib=0.9.0=r43hc72bb7e_0
  - r-cachem=1.1.0=r43hb1dbf0f_1
  - r-callr=3.7.6=r43hc72bb7e_1
  - r-cellranger=1.1.0=r43hc72bb7e_1007
  - r-circlize=0.4.16=r43hc72bb7e_1
  - r-cli=3.6.3=r43h0d4f4ea_1
  - r-clipr=0.8.0=r43hc72bb7e_3
  - r-colorspace=2.1_1=r43hdb488b9_0
  - r-conflicted=1.2.0=r43h785f33e_2
  - r-cpp11=0.5.1=r43hc72bb7e_0
  - r-crayon=1.5.3=r43hc72bb7e_1
  - r-curl=6.0.1=r43h2700575_0
  - r-data.table=1.16.4=r43he23165d_0
  - r-dbi=1.2.3=r43hc72bb7e_1
  - r-dbplyr=2.5.0=r43hc72bb7e_1
  - r-digest=0.6.37=r43h0d4f4ea_0
  - r-dplyr=1.1.4=r43h0d4f4ea_1
  - r-dtplyr=1.3.1=r43hc72bb7e_2
  - r-ellipsis=0.3.2=r43hb1dbf0f_3
  - r-evaluate=1.0.3=r43hc72bb7e_0
  - r-fansi=1.0.6=r43hb1dbf0f_1
  - r-farver=2.1.2=r43ha18555a_1
  - r-fastmap=1.2.0=r43ha18555a_1
  - r-findpython=1.0.9=r43hc72bb7e_0
  - r-fontawesome=0.5.3=r43hc72bb7e_0
  - r-forcats=1.0.0=r43hc72bb7e_2
  - r-fs=1.6.5=r43h93ab643_0
  - r-gargle=1.5.2=r43h785f33e_1
  - r-generics=0.1.3=r43hc72bb7e_3
  - r-ggplot2=3.5.1=r43hc72bb7e_1
  - r-globaloptions=0.1.2=r43ha770c72_3
  - r-glue=1.8.0=r43h2b5f3a1_0
  - r-googledrive=2.1.1=r43hc72bb7e_2
  - r-googlesheets4=1.1.1=r43h785f33e_2
  - r-gtable=0.3.6=r43hc72bb7e_0
  - r-haven=2.5.4=r43h0d4f4ea_1
  - r-highr=0.11=r43hc72bb7e_1
  - r-hms=1.1.3=r43hc72bb7e_2
  - r-htmltools=0.5.8.1=r43ha18555a_1
  - r-httr=1.4.7=r43hc72bb7e_1
  - r-ids=1.0.1=r43hc72bb7e_4
  - r-isoband=0.2.7=r43ha18555a_3
  - r-jquerylib=0.1.4=r43hc72bb7e_3
  - r-jsonlite=1.8.9=r43h2b5f3a1_0
  - r-knitr=1.49=r43hc72bb7e_0
  - r-labeling=0.4.3=r43hc72bb7e_1
  - r-lattice=0.22_6=r43hb1dbf0f_1
  - r-lifecycle=1.0.4=r43hc72bb7e_1
  - r-lubridate=1.9.4=r43h2b5f3a1_0
  - r-magrittr=2.0.3=r43hb1dbf0f_3
  - r-mass=7.3_60=r43h76d94ec_0
  - r-matrix=1.6_1.1=r43h76d94ec_0
  - r-memoise=2.0.1=r43hc72bb7e_3
  - r-mgcv=1.9_1=r43h0d28552_1
  - r-mime=0.12=r43hb1dbf0f_3
  - r-modelr=0.1.11=r43hc72bb7e_2
  - r-munsell=0.5.1=r43hc72bb7e_1
  - r-nlme=3.1_167=r43hb67ce94_0
  - r-openssl=2.2.2=r43he8289e2_0
  - r-pillar=1.10.1=r43hc72bb7e_0
  - r-pkgconfig=2.0.3=r43hc72bb7e_4
  - r-prettyunits=1.2.0=r43hc72bb7e_1
  - r-processx=3.8.5=r43h2b5f3a1_0
  - r-progress=1.2.3=r43hc72bb7e_1
  - r-ps=1.8.1=r43h2b5f3a1_0
  - r-purrr=1.0.2=r43hdb488b9_1
  - r-r6=2.5.1=r43hc72bb7e_3
  - r-ragg=1.3.3=r43h9aa3752_0
  - r-rappdirs=0.3.3=r43hb1dbf0f_3
  - r-rcolorbrewer=1.1_3=r43h785f33e_3
  - r-readr=2.1.5=r43h0d4f4ea_1
  - r-readxl=1.4.3=r43he58e087_1
  - r-rematch=2.0.0=r43hc72bb7e_1
  - r-rematch2=2.1.2=r43hc72bb7e_4
  - r-reprex=2.1.1=r43hc72bb7e_1
  - r-rlang=1.1.5=r43h93ab643_0
  - r-rmarkdown=2.29=r43hc72bb7e_0
  - r-rstudioapi=0.17.1=r43hc72bb7e_0
  - r-rvest=1.0.4=r43hc72bb7e_1
  - r-sass=0.4.9=r43ha18555a_1
  - r-scales=1.3.0=r43hc72bb7e_1
  - r-selectr=0.4_2=r43hc72bb7e_4
  - r-shape=1.4.6.1=r43ha770c72_1
  - r-stringi=1.8.4=r43h33cde33_3
  - r-stringr=1.5.1=r43h785f33e_1
  - r-sys=3.4.3=r43h2b5f3a1_0
  - r-systemfonts=1.2.1=r43h5c043a3_0
  - r-textshaping=0.3.7=r43h884c59f_0
  - r-tibble=3.2.1=r43hdb488b9_3
  - r-tidyr=1.3.1=r43h0d4f4ea_1
  - r-tidyselect=1.2.1=r43hc72bb7e_1
  - r-tidyverse=2.0.0=r43h785f33e_2
  - r-timechange=0.3.0=r43ha18555a_1
  - r-tinytex=0.54=r43hc72bb7e_0
  - r-tzdb=0.4.0=r43ha18555a_2
  - r-utf8=1.2.4=r43hb1dbf0f_1
  - r-uuid=1.2_1=r43hdb488b9_0
  - r-vctrs=0.6.5=r43h0d4f4ea_1
  - r-viridislite=0.4.2=r43hc72bb7e_2
  - r-vroom=1.6.5=r43h0d4f4ea_1
  - r-withr=3.0.2=r43hc72bb7e_0
  - r-xfun=0.50=r43h93ab643_0
  - r-xml2=1.3.6=r43h8194278_2
  - r-yaml=2.3.10=r43hdb488b9_0
  - readline=8.2=h8228510_1
  - scipy=1.15.1=py312h180e4f1_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sed=4.8=he412f7d_0
  - setuptools=75.8.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - statsmodels=0.14.4=py312hc0a28a1_0
  - sysroot_linux-64=2.12=he073ed8_17
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - tornado=6.4.2=py312h66e93f0_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025a=h78e105d_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - wayland=1.23.1=h3e06ad9_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zstd=1.5.6=ha6fb4c9_0
