references:
  genomic_fna: '/storage1/gabe/ems_effect_code/data/references/GCF_000008025.1_ASM802v1_genomic.fna.gz'
  annotation: '/storage1/gabe/ems_effect_code/data/references/GCF_000008025.1_ASM802v1_genomic.gff'
  codon_table: '/storage1/gabe/ems_effect_code/data/references/11.json'
  prov_score_db: '/storage1/gabe/ems_effect_code/data/provean_database/provean.db'

provean:
  data_dir: '/storage1/gabe/ems_effect_code/data/provean_sets'
  executable: '/storage1/gabe/ems_effect_code/provean/provean.sh'
  num_threads: 75